### ISSUE TITLE
KeyError: 82 and Reading header timeout

### ISSUE THREAD

**Issue by huseyinturen** [mathiasfrey/ecrterm#13]
Hello everyone,

Some errors occur when I try to run the code on my device. I just want to read card via cvend. What do these errors mean?

read card
![read card_code](https://user-images.githubusercontent.com/52621031/187866064-dd526988-c9c8-41df-a81d-228ab1ff2bf3.JPG)
Output
![read card](https://user-images.githubusercontent.com/52621031/187866100-89330eda-c8dc-4a9c-9c77-0a3ac76a7d56.JPG)

register before payment
![register(0x08) before payment_code](https://user-images.githubusercontent.com/52621031/187866260-10e73daf-4558-4ac5-bbf9-7f4393581fe2.JPG)
Output
![register(0x08) before payment](https://user-images.githubusercontent.com/52621031/187866162-67ef0827-fc51-4805-adfa-24c423108c4d.JPG)

register before status
![register(0x08) before status_code](https://user-images.githubusercontent.com/52621031/187866312-7431eb62-4735-4347-a366-bf42e8098923.JPG)
Output
![register(0x08) before status](https://user-images.githubusercontent.com/52621031/187866398-0f234d74-9fc2-4ed7-a446-a2b216e89d10.JPG)

**Comment by g4borg** [comment]
This software is atm. not maintained, and there are forks that are more actively maintained.

I suggest either adding the missing Bitmap entry into BITMAPS, or rewriting the BITMAPS[bitmap_type] to something along `BITMAPS.get(bitmap_type) or (None, None, None)` and react to a NoneValue there.
