### ISSUE TITLE
TCP Support

### ISSUE THREAD

**Issue by t-oster** [mathiasfrey/ecrterm#4]
Hi,

Your library is the only Open Source ZVT Library I could find. I'm about to use it for operating our Terminal via TCP. Maybe you already have an unfinished tcp_transport.py file around, where I can start from?

**Comment by mcules** [comment]
Do you would do here anything else?
Could use TCP also quite good;)

**Comment by t-oster** [comment]
Well... my solution was to use OPI (https://de.wikipedia.org/wiki/Open_Payment_Initiative) instead of ZVT, so for me this issue is not important anymore. @mcules feel free to reopen it if you are hoping for a solution.

**Comment by mcules** [comment]
Could it used with the Ingenico Terminals directly?

**Comment by g4borg** [comment]
I still think TCP support is a valid ticket anyway. The basic design of the library was with a later TCP expansion in mind. It is more a question of time and fundings, to add it properly and tested, I would say;
I think for some applications of ecrterm this is even an upside, as adding your custom transmission class, and deciding how to use network (library choices) can be quite application dependant, while the serial usage is straightforward, and always "blocking".

**Comment by karolyi** [comment]
@t-oster do you have any documentation for OPI? it seems the links on wincor-nixdorf's site are all dead.

**Comment by t-oster** [comment]
Well, I do have a PDF but I had to sign for it. However I think my little helper class may give you a hint https://gist.github.com/t-oster/a1bed2bb82d566bbdb90706d521a8f83.

**Comment by karolyi** [comment]
@t-oster thx. one would think 'open' in the OPI means it's easy to find documentation for it.

also, I see you are only connecting to the POS terminal, and not accepting connections from it. I still don't have documentation for the original OPI but I have one for the CCV extended protocol, which defines a channel where the POS terminal connects back to the device/computer connecting to it, on port 20007 per default. isn't it necessary for proper communication? how do you get the success or failure response for the transaction?

**Comment by t-oster** [comment]
As you see in https://gist.github.com/t-oster/a1bed2bb82d566bbdb90706d521a8f83#file-opihelper-php-L105 the method returns a text containing `'OverallResult="Aborted"` or `'OverallResult="Success"`. The connection is bi-directional, why should there be a need of a separate connection backwards? However it is long ago when I implemented this.
I also was dissapointed that the documentation is not as **Open** as the name indicates.
I was able to initiate payments with this class, and if I hadn't signed a contract, I would post the specification (if I find it).

**Comment by karolyi** [comment]
thanks, I'll look into it. it might be that the backwards connecting channel on port 20007 called `DeviceRequests` is only part of the CCV extended version. the firmware in the terminals is called 'SecPos', and it uses an extended OPI protocol. since I haven't seen the original spec, I can't know if it's there too.

I'm implementing something python based for this protocol, but I know PHP, so your code is helping, thank you. :)

**Comment by t-oster** [comment]
Maybe you should contact Juergen.Manske [at ]wincor-nixdorf.com. He sent me the specification some time ago together with the Non-Disclosure-Agreement

**Comment by karolyi** [comment]
Ah yes, I found him yesterday after extensive googling, and I had to go to archive.org for the older version of wincor-nixdorf's website, since all the links to their site from wikipedia are broken. they might have just replaced their site.

**Comment by t-oster** [comment]
please do not mention me and remove the comment, because the NDA also states that I may not talk about its existence
